language: node_js
node_js:
  - "5"

services:
  - docker

before_script:
  - npm -s i

script:
  - npm -s test

after_success:
  - npm run -s build
  - docker build -t storyxpress/react-node-starter:latest .
